import { Counter } from "@/app/counter";
import Image from "next/image";
import gambarKucing from "@/public/kucing.jpg"
import type { Metadata } from "next";

export const metadata: Metadata = { //?mengubah metadata perhalaman
  title: "Test",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <div>
      <h1>Home</h1> {/*? //?server componen (karena tidak ada layout / static) */}
      <Counter /> {/* //?client componen (karena ada layout/abstract / dinamis) */}
      {/* <Image
        width={200}
        height={200}
        alt="Gambar Kucing"
        src="https://plus.unsplash.com/premium_photo-1677101221533-52b45823a2dc?q=80&w=1742&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D" />

    </div> */}
      {/*<Image src={gambarKucing} alt="gambar kucing" />  ?width dan height opsional dan lebih enak */}

      {/* butuh class relative, karena imagenya absolute (agar tidak mengambil titik pinggir di viewport) */}
      <div className="relative w-72 h-72 rounded-full overflow-hidden">
        <Image src={gambarKucing}
          alt="gambar kucing"
          fill
          placeholder="blur"
          // blurDataURL="isi disini, error karena kepanjangan, harus di convert dulu"
          // loading="eager" //? eager (agar gambar langsung di load)
          loading="lazy" //? lazy (agar gambar di load ketika di scroll)
          className="object-cover" /> {/* ?width dan height opsional dan lebih enak */}


      </div>
      
    </div>
  );
}